/**
 * Do not edit this file manually, it will be overwritten by IDE
 */
require(['environment', 'rpc'], function (F, Rpc) {
    var global = this;
    F.cacheBust(true);
    //F.export(global);
    
    Rpc.requireRemotes("BusinessModule", function (bm) {
        bm.calculatePayment(10, function (value) {
           // console.info(value);
        }, function (e) {
            
        });
    }, function (e) {
        
    });
});